
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: hostnic-ipam-config
  namespace: kube-system
data:
  subnet-auto-assign: "off"
  ipam: |
    {
      "Default": ["vxnet-xxxxxxxx"],
      "test": ["4100-172-16-3-0-26", "4100-172-16-3-128-26"],
      "abc": ["4100-172-16-3-64-26", "4100-172-16-3-192-26"]
    }

---

apiVersion: network.qingcloud.com/v1alpha1
kind: VxNetPool
metadata:
  name: v-pool
spec:
  vxnets:
    - name: vxnet-xxxxxxxx
    - name: vxnet-yyyyyyyy
  blockSize: 27

---
