apiVersion: v1
kind: Pod
metadata:
  name: fixip-pod
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"192.168.102.40\"]" #fix your customer IP,IP must belong to
    # 'hostnic-ipam-config' subnet
spec:
  containers:
  - image: nginx
    name: nginx
    livenessProbe:
      httpGet:
        path: /
        port: 80
