
---

apiVersion: v1
kind: Service
metadata:
  name: hostnic-svc
  namespace: kube-system
  labels:
    app: hostnic-node
spec:
  selector:
    app: hostnic-node
  ports:
    - protocol: TCP
      port: 9191         
      targetPort: 9191
      name: hostnic-metrics-port
  type: ClusterIP

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hostnic
  namespace: kube-system
spec:
  endpoints:
    - interval: 1m
      port: hostnic-metrics-port
      scheme: http
  selector:
    matchLabels:
      app: hostnic-node

---

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-qke-hostnic-rules
  namespace: kubesphere-monitoring-system
spec:
  groups:
  - name: hostnic
    rules:
    - alert: hostnic-vxnet-ipam
      annotations:
        message: there are not many IP addresses left in vxnet {{ $labels.vxnet_name}}
        summary: lack of IP addresses in vxnet
      expr: max(hostnic_ipam_vxnet_allocator) by(vxnet_name) / max(hostnic_ipam_vxnet_total)
        by(vxnet_name) > 0.8
      for: 5m
      labels:
        severity: warning
    - alert: hostnic-namespace-ipam
      annotations:
        message: there are no more IP addresses left in namespace {{ $labels.ns_name}}
        summary: lack of IP addresses in namespace
      expr: max(hostnic_ipam_namespace_total - hostnic_ipam_namespace_allocator) by(ns_name) == 0
      for: 5m
      labels:
        severity: warning
    - alert: hostnic-ipam-alloc-from-block-failed
      annotations:
        message: ipam alloc from block failed in node {{ $labels.node_name}}
        summary: hostnic ipam alloc from block failed
      expr: min(irate(hostnic_ipam_alloc_from_block_failed[5m])) by(node_name) > 0
      for: 5m
      labels:
        severity: warning
    - alert: hostnic-ipam-alloc-from-host-failed
      annotations:
        message: ipam alloc from host failed in node {{ $labels.node_name}}
        summary: hostnic ipam alloc from host failed
      expr: min(irate(hostnic_ipam_alloc_from_host_failed[5m])) by(node_name) > 0
      for: 5m
      labels:
        severity: warning
    - alert: hostnic-ipam-alloc-resource-notfound
      annotations:
        message: ipam resource notfound in node {{ $labels.node_name}}
        summary: hostnic ipam alloc resource notfound
      expr: min(irate(hostnic_ipam_alloc_resource_notfound[5m])) by(node_name) > 0
      for: 5m
      labels:
        severity: warning
    - alert: hostnic-attach-failed
      annotations:
        message: hostnic nic attach failed for vxnet {{ $labels.vxnet_name}} in node {{ $labels.node_name}}
        summary: hostnic nic attach failed
      expr: |
        sum(hostnic_vxnet_count{phase!="Succeeded"}) by(vxnet_name) > 0
      for: 5m
      labels:
        severity: warning
    - alert: hostnic-ipam-free-from-host-failed  
      annotations:
        message: ipam free from host failed in node {{ $labels.node_name}}
        summary: hostnic ipam free from host failed
      expr: min(irate(hostnic_ipam_free_from_host_failed[5m])) by(node_name) > 0
      for: 5m
      labels:
        severity: warning
    - alert: hostnic-ipam-free-from-pool-failed
      annotations:
        message: ipam free from pool failed in node {{ $labels.node_name}}
        summary: hostnic ipam free from pool failed
      expr: min(irate(hostnic_ipam_free_from_pool_failed[5m])) by(node_name) > 0
      for: 5m
      labels:
        severity: warning
    - alert: hostnic-ipam-alloc-from-pool-failed
      annotations:
        message: ipam alloc from pool failed in node {{ $labels.node_name}}
        summary: hostnic ipam alloc from pool failed
      expr: |
        min(irate(hostnic_ipam_alloc_from_pool_failed[5m])) by(node_name) > 0
      for: 5m
      labels:
        severity: warning
